BOARD_TAG	= nano

MONITOR_PORT	= /dev/ttyUSB0
MONITOR_BAUDRATE= 38400
ARDUINO_LIBS	+= MsTimer2 Wire SPI Adafruit_BMP280_Library SoftwareSerial

include ../common.mk
include /usr/share/arduino/Arduino.mk
